from __future__ import annotations

from typing import Any, Protocol


class AppRepository(Protocol):
    async def find_user_public(self, username: str) -> dict[str, Any] | None: ...
    async def find_user_with_password(self, username: str) -> dict[str, Any] | None: ...
    async def create_user(self, username: str, password: str) -> None: ...
    async def update_user_avatar(self, username: str, avatar_url: str) -> None: ...

    async def insert_refresh_token(self, payload: dict[str, Any]) -> None: ...
    async def find_active_refresh_token(self, jti: str) -> dict[str, Any] | None: ...
    async def revoke_refresh_token(self, jti: str, reason: str) -> None: ...

    async def load_history_snapshot(self, username: str) -> dict[str, Any]: ...
    async def clear_conversation_messages(self, username: str, conversation_id: str) -> None: ...
    async def delete_conversation(self, username: str, conversation_id: str) -> None: ...
    async def update_conversation(self, username: str, conversation_id: str, patch: dict[str, Any]) -> None: ...
    async def clear_user_history(self, username: str) -> None: ...

    async def get_custom_models(self, username: str) -> list[dict[str, Any]]: ...
    async def set_custom_models(self, username: str, models: list[dict[str, Any]]) -> None: ...

    async def persist_user_message(
        self,
        username: str,
        conversation_id: str,
        message: str,
        attachments: list[dict[str, Any]],
        model: str,
    ) -> None: ...

    async def persist_assistant_message(
        self,
        username: str,
        conversation_id: str,
        content: str,
        refs: list[dict[str, Any]],
        context_docs: list[dict[str, Any]],
        retrieval_mode_used: str,
        usage: dict[str, Any] | None,
    ) -> None: ...
